#!/bin/bash

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")

# SIGUSR1 trap (forward signal)
_usr1() {
  kill -n 10 "$child" 2>/dev/null
}
trap _usr1 SIGUSR1

# SIGTERM trap (forward signal)
_term() {
  kill -TERM "$child" 2>/dev/null
}
trap _term SIGTERM

$SCRIPTPATH/venv/bin/python3 $SCRIPTPATH/cmd.py "$@" &
child=$!
wait "$child"
